source("load_data.R")
data <- load_dataset()
source("plot1.R")
source("plot2.R")
source("plot3.R")
source("plot4.R")
 message("Draw plot 1.")
plot1(data)
 message("Draw plot 2.")
plot2(data)
 message("Draw plot 3.")
plot3(data)
 message("Draw plot 4.")
plot4(data)
 message("Done.")